// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5X_Mn45hWiBPDBuVzB28USYCSLD6CVQ',
    appId: '1:611840348446:web:8e7e0509f51b416c8df90f',
    messagingSenderId: '611840348446',
    projectId: 'cartafri-ad8e1',
    authDomain: 'cartafri-ad8e1.firebaseapp.com',
    storageBucket: 'cartafri-ad8e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9rN5NE17Al8e1_0LMUd8i7GB5BhENpUs',
    appId: '1:611840348446:android:c523e83fbb3b39038df90f',
    messagingSenderId: '611840348446',
    projectId: 'cartafri-ad8e1',
    storageBucket: 'cartafri-ad8e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACyaZnbPrSHdLPM3d3hJEODj0wzdBQ_sc',
    appId: '1:611840348446:ios:a3bc184b6e0c22e68df90f',
    messagingSenderId: '611840348446',
    projectId: 'cartafri-ad8e1',
    storageBucket: 'cartafri-ad8e1.appspot.com',
    androidClientId: '611840348446-i0mer62i93tni42p555fd4f2jrcavru3.apps.googleusercontent.com',
    iosClientId: '611840348446-vm6kvqbj60ot8e7he24odilujcdl7mmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartafri',
  );
}
